#include <stdio.h>  

int main(){
    int maximum = 4000000   ;
    int sum = 2;
    int x = 1;
    int y = 2; /*first two terms of fib*/
    int z = 0;
    while (z < maximum){
        z = x + y;
        if (z % 2 == 0 ){
            sum += z;
        }
        if (x > y){
            y = z;
        }
        else {
            x = z;
        }
    }
    printf("Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.\n\n");
    printf("%d\n", sum);
} 
